/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description Health check endpoint.
     */
    get: operations['health_check_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/uploads': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Upload
     * @description Initiate a resumable multipart upload to S3.
     */
    post: operations['create_upload_api_uploads_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/uploads/{video_key}/parts:sign': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sign Parts
     * @description Return short-lived presigned PUT URLs for a batch of part numbers.
     */
    post: operations['sign_parts_api_uploads__video_key__parts_sign_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/uploads/{video_key}/parts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Parts
     * @description List parts already received by S3 — used to resume an interrupted upload.
     */
    get: operations['list_parts_api_uploads__video_key__parts_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/uploads/{video_key}/complete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Complete Upload
     * @description Validate all parts are present and finalize the S3 multipart upload.
     */
    post: operations['complete_upload_api_uploads__video_key__complete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/videos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Videos
     * @description List videos with optional category/status filters and cursor pagination.
     */
    get: operations['list_videos_api_videos_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/videos/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Categories
     * @description List the distinct video categories.
     */
    get: operations['list_categories_api_videos_categories_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/videos/{video_key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Video
     * @description Full metadata for a single video, including the manifest path when ready.
     */
    get: operations['get_video_api_videos__video_key__get']
    put?: never
    post?: never
    /**
     * Delete Video
     * @description Hard delete: permanently remove the video's S3 objects and metadata.
     */
    delete: operations['delete_video_api_videos__video_key__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/videos/{video_key}/hide': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Hide Video
     * @description Soft delete: hide the video from listings without removing its files.
     */
    post: operations['hide_video_api_videos__video_key__hide_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/videos/{video_key}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Restore Video
     * @description Undo a soft delete: make the video visible in listings again.
     */
    post: operations['restore_video_api_videos__video_key__restore_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/videos/{video_key}/dash/{filename}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Dash File
     * @description Stream a DASH manifest or segment from S3 with range support.
     */
    get: operations['get_dash_file_api_videos__video_key__dash__filename__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/videos/{video_key}/assets/{filename}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Asset
     * @description Stream a thumbnail asset (poster.jpg, sprite.jpg, thumbnails.vtt) from S3.
     */
    get: operations['get_asset_api_videos__video_key__assets__filename__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ApiResponse[CategoryListData] */
    ApiResponse_CategoryListData_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['CategoryListData'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[CompleteUploadResponse] */
    ApiResponse_CompleteUploadResponse_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['CompleteUploadResponse'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[DeleteVideoData] */
    ApiResponse_DeleteVideoData_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['DeleteVideoData'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[HealthData] */
    ApiResponse_HealthData_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['HealthData'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[InitiateUploadResponse] */
    ApiResponse_InitiateUploadResponse_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['InitiateUploadResponse'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[ListPartsResponse] */
    ApiResponse_ListPartsResponse_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['ListPartsResponse'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[SignPartsResponse] */
    ApiResponse_SignPartsResponse_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['SignPartsResponse'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[VideoDetail] */
    ApiResponse_VideoDetail_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['VideoDetail'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[VideoListData] */
    ApiResponse_VideoListData_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['VideoListData'] | null
      /** Error */
      error?: string | null
    }
    /** ApiResponse[VideoVisibilityData] */
    ApiResponse_VideoVisibilityData_: {
      /**
       * Success
       * @default true
       */
      success: boolean
      data?: components['schemas']['VideoVisibilityData'] | null
      /** Error */
      error?: string | null
    }
    /** CategoryListData */
    CategoryListData: {
      /** Categories */
      categories: string[]
    }
    /** CompletePart */
    CompletePart: {
      /** Part Number */
      part_number: number
      /** Etag */
      etag: string
    }
    /** CompleteUploadRequest */
    CompleteUploadRequest: {
      /** Upload Id */
      upload_id: string
      /** Parts */
      parts: components['schemas']['CompletePart'][]
    }
    /** CompleteUploadResponse */
    CompleteUploadResponse: {
      /** Video Key */
      video_key: string
    }
    /** DeleteVideoData */
    DeleteVideoData: {
      /** Video Key */
      video_key: string
      /**
       * Deleted
       * @default true
       */
      deleted: boolean
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthData */
    HealthData: {
      /** Status */
      status: string
    }
    /** InitiateUploadRequest */
    InitiateUploadRequest: {
      /** Filename */
      filename: string
      /** Content Type */
      content_type: string
      /**
       * Size
       * @description Total file size in bytes
       */
      size: number
      /** Title */
      title: string
      /** Category */
      category: string
    }
    /** InitiateUploadResponse */
    InitiateUploadResponse: {
      /** Video Key */
      video_key: string
      /** Upload Id */
      upload_id: string
      /** Part Size */
      part_size: number
      /** Part Count */
      part_count: number
    }
    /** ListPartsResponse */
    ListPartsResponse: {
      /** Parts */
      parts: components['schemas']['UploadedPart'][]
      /** Part Count */
      part_count: number
    }
    /** SignPartsRequest */
    SignPartsRequest: {
      /** Upload Id */
      upload_id: string
      /** Part Numbers */
      part_numbers: number[]
    }
    /** SignPartsResponse */
    SignPartsResponse: {
      /** Urls */
      urls: {
        [key: string]: string
      }
      /** Expires In */
      expires_in: number
    }
    /** UploadedPart */
    UploadedPart: {
      /** Part Number */
      part_number: number
      /** Etag */
      etag: string
      /** Size */
      size: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * VideoDetail
     * @description Full metadata for the detail page. Still omits internal upload fields.
     */
    VideoDetail: {
      /** Video Key */
      video_key: string
      /** Title */
      title: string
      /** Category */
      category: string
      /** Status */
      status: string
      /** Created At */
      created_at: string
      /** Updated At */
      updated_at: string
      /** Original Filename */
      original_filename: string
      /** Size */
      size: number
      /** Duration Seconds */
      duration_seconds?: number | null
      /**
       * Resolutions
       * @default []
       */
      resolutions: string[]
      /** Error Message */
      error_message?: string | null
      /** Manifest Path */
      manifest_path?: string | null
      /** Poster Path */
      poster_path?: string | null
      /** Thumbnails Vtt Path */
      thumbnails_vtt_path?: string | null
    }
    /** VideoListData */
    VideoListData: {
      /** Items */
      items: components['schemas']['VideoSummary'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /**
     * VideoSummary
     * @description Public listing shape — omits internal fields (upload_id, lease, etc.).
     */
    VideoSummary: {
      /** Video Key */
      video_key: string
      /** Title */
      title: string
      /** Category */
      category: string
      /** Status */
      status: string
      /** Created At */
      created_at: string
      /** Duration Seconds */
      duration_seconds?: number | null
      /**
       * Resolutions
       * @default []
       */
      resolutions: string[]
      /** Poster Path */
      poster_path?: string | null
    }
    /** VideoVisibilityData */
    VideoVisibilityData: {
      /** Video Key */
      video_key: string
      /** Visibility */
      visibility: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_check_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_HealthData_']
        }
      }
    }
  }
  create_upload_api_uploads_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InitiateUploadRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_InitiateUploadResponse_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  sign_parts_api_uploads__video_key__parts_sign_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        video_key: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignPartsRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_SignPartsResponse_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_parts_api_uploads__video_key__parts_get: {
    parameters: {
      query: {
        upload_id: string
      }
      header?: never
      path: {
        video_key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_ListPartsResponse_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  complete_upload_api_uploads__video_key__complete_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        video_key: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompleteUploadRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_CompleteUploadResponse_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_videos_api_videos_get: {
    parameters: {
      query?: {
        category?: string | null
        status?: string | null
        limit?: number
        cursor?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_VideoListData_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_categories_api_videos_categories_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_CategoryListData_']
        }
      }
    }
  }
  get_video_api_videos__video_key__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        video_key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_VideoDetail_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_video_api_videos__video_key__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        video_key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_DeleteVideoData_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  hide_video_api_videos__video_key__hide_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        video_key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_VideoVisibilityData_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  restore_video_api_videos__video_key__restore_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        video_key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponse_VideoVisibilityData_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_dash_file_api_videos__video_key__dash__filename__get: {
    parameters: {
      query?: never
      header?: {
        Range?: string | null
      }
      path: {
        video_key: string
        filename: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_asset_api_videos__video_key__assets__filename__get: {
    parameters: {
      query?: never
      header?: {
        Range?: string | null
      }
      path: {
        video_key: string
        filename: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
