"""Read + management side of the catalog: listing, categories, deletes."""

from datetime import UTC, datetime
from typing import TYPE_CHECKING, Annotated, Any

from fastapi import Depends, HTTPException, status

from app.common.deps import S3ClientDep, SettingsDep
from app.core.categories import get_allowed_categories

if TYPE_CHECKING:
    from types_aiobotocore_s3.type_defs import ObjectIdentifierTypeDef
from app.modules.videos.schemas import (
    CategoryListData,
    DeleteVideoData,
    VideoDetail,
    VideoListData,
    VideoSummary,
    VideoVisibilityData,
)
from app.repositories.video_repository import (
    VISIBILITY_ACTIVE,
    VISIBILITY_INACTIVE,
    VideoRecord,
    VideoRepositoryDep,
    VideoStatus,
)


def _now() -> str:
    return datetime.now(UTC).isoformat()


def _upload_prefix(video_key: str) -> str:
    """All S3 objects for a video live under this prefix (raw + dash/)."""
    return f"uploads/{video_key}/"


class VideoCatalogService:
    def __init__(
        self,
        video_repo: VideoRepositoryDep,
        s3: S3ClientDep,
        settings: SettingsDep,
    ) -> None:
        self._video_repo = video_repo
        self._s3 = s3
        self._settings = settings

    async def list_videos(
        self,
        *,
        category: str | None,
        status_filter: str | None,
        limit: int,
        cursor: str | None,
    ) -> VideoListData:
        try:
            page = await self._video_repo.list_videos(
                category=category,
                status=status_filter,
                limit=limit,
                cursor=cursor,
            )
        except ValueError as exc:
            raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, str(exc))

        return VideoListData(
            items=[
                VideoSummary.from_record(r, poster_path=self._poster_path(r))
                for r in page.items
            ],
            next_cursor=page.next_cursor,
        )

    def _base_path(self, video_key: str) -> str:
        return f"{self._settings.api_prefix}/videos/{video_key}"

    def _poster_path(self, record: VideoRecord) -> str | None:
        """Poster URL, only once ready (assets are generated by the worker)."""
        if record.status != VideoStatus.READY:
            return None
        return f"{self._base_path(record.video_key)}/assets/poster.jpg"

    async def get_video(self, video_key: str) -> VideoDetail:
        record = await self._video_repo.get(video_key)
        if record is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "Video not found")

        manifest_path: str | None = None
        thumbnails_vtt_path: str | None = None
        if record.status == VideoStatus.READY:
            base = self._base_path(video_key)
            manifest_path = f"{base}/dash/manifest.mpd"
            thumbnails_vtt_path = f"{base}/assets/thumbnails.vtt"
        return VideoDetail.from_record(
            record,
            manifest_path=manifest_path,
            poster_path=self._poster_path(record),
            thumbnails_vtt_path=thumbnails_vtt_path,
        )

    async def list_categories(self) -> CategoryListData:
        # The predefined catalog, not a scan of stored data.
        return CategoryListData(categories=list(get_allowed_categories()))

    async def set_visibility(
        self, video_key: str, visibility: str
    ) -> VideoVisibilityData:
        """Soft delete (inactive) or restore (active)."""
        found = await self._video_repo.set_visibility(video_key, visibility, _now())
        if not found:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "Video not found")
        return VideoVisibilityData(video_key=video_key, visibility=visibility)

    async def delete_video(self, video_key: str) -> DeleteVideoData:
        """Hard delete: remove all S3 objects, then the metadata record."""
        record = await self._video_repo.get(video_key)
        if record is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "Video not found")

        # A worker may still be writing DASH output; deleting now would race it
        # and orphan segments. Hide it instead, or wait for processing to finish.
        if record.status == VideoStatus.PROCESSING:
            raise HTTPException(
                status.HTTP_409_CONFLICT,
                "Video is processing — hide it instead, or retry after it finishes",
            )

        # S3 first, then the row — a partial S3 failure leaves the record so the
        # delete can be safely retried rather than orphaning storage.
        await self._delete_s3_prefix(_upload_prefix(video_key))
        await self._video_repo.delete(video_key)
        return DeleteVideoData(video_key=video_key)

    async def _delete_s3_prefix(self, prefix: str) -> None:
        bucket = self._settings.s3_bucket
        token: str | None = None
        while True:
            kwargs: dict[str, Any] = {"Bucket": bucket, "Prefix": prefix}
            if token:
                kwargs["ContinuationToken"] = token
            listing = await self._s3.list_objects_v2(**kwargs)

            objects: list["ObjectIdentifierTypeDef"] = [
                {"Key": key}
                for o in listing.get("Contents", [])
                if (key := o.get("Key"))
            ]
            if objects:
                await self._s3.delete_objects(
                    Bucket=bucket, Delete={"Objects": objects}
                )

            if listing.get("IsTruncated"):
                token = listing.get("NextContinuationToken")
            else:
                break


VideoCatalogServiceDep = Annotated[VideoCatalogService, Depends()]


# Exposed so the router can map endpoints to visibility values.
SOFT_DELETE_VISIBILITY = VISIBILITY_INACTIVE
RESTORE_VISIBILITY = VISIBILITY_ACTIVE
